spring:
  application:
    name: order-service
    
#server:
#  port: 8201
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka1:2002/eureka


# ribbon 重试和 hystrix 超时这里没有设置，采用了默认值
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
          
---
spring:
  profiles: order-service1
  
server:
  port: 8201
---
spring:
  profiles: order-service2
  
server:
  port: 8202

